FROM occlum/occlum:latest-ubuntu22.04
LABEL authors="Vencel Bajnok"
LABEL maintainer="bajnokvencel@edu.bme.hu"
LABEL description="Docker image for verifying SGX enclaves using Occlum."
LABEL version="1.0.0"

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu:/opt/occlum/glibc/lib

WORKDIR /app

COPY src/client/verification.c /app/src/client/verification.c
RUN cp /opt/occlum/toolchains/dcap_lib/glibc/libocclum_dcap.so.0.1.0 /opt/occlum/glibc/lib

WORKDIR /app/src/client/

RUN LD=ld gcc verification.c -fPIE -pie -o verification -L "/opt/occlum/toolchains/dcap_lib/glibc" -locclum_dcap -I /opt/intel/sgxsdk/include -I "/opt/occlum/toolchains/dcap_lib/inc" -lssl -lcrypto

RUN sed -i 's|https://localhost:8081/sgx/certification/v4/|https://api.trustedservices.intel.com/sgx/certification/v4/|g' /etc/sgx_default_qcnl.conf

ENTRYPOINT ["/app/src/client/verification"]
