@startuml
left to right direction
skinparam nodesep 40
skinparam ranksep 40

cloud "Cloud" as cloud{
    component "Intel PCCS Service" as pccs_service
    interface "PCCS API" as pccs_api
}

actor "End User" as user

node "Remote Device" {
    component "Client Software" as client_app
}

node "Host Server" {

    component "Enclave Proxy\nServer" as proxy

    database "Database" as db

    package "Trusted Execution Env (TEE)" {
        component "Verification Job\n[Enclave A]" as enclave1 #LightGreen
        component "Verification Job\n[Enclave B]" as enclave2 #LightGreen
    }

    ' -- Interface Definitions --

    interface "HTTP/REST API" as http_int
    interface "SQL / TCP" as db_int
    interface "Enclave Call\n(ECALL)" as enclave_int
    interface "TCP API" as tcp_api
}

' --- Relationships ---

user --> client_app : Input data
user --( pccs_api : Verify quote
pccs_service -- pccs_api : <<provides>>

http_int - proxy : <<provides>>
client_app --( http_int : <<uses>>

db_int - db : <<provides>>
proxy --( db_int : <<uses>>

enclave_int -- enclave1 : <<provides>>
tcp_api -- enclave1 : <<provides>>
enclave_int -- enclave2 : <<provides>>
tcp_api -- enclave2 : <<provides>>

proxy --( enclave_int : Dispatch
proxy --( tcp_api : <<uses>>

@enduml